import './slider.js';
import './team.js';
import './products.js';
import './reviews.js';
import './player.js';
import './form.js';
import './map.js';
import './fixed-menu.js';
import './mobile-menu.js';
